# Site settings
title: Rob Writes Code
description: > # this means to ignore newlines until "baseurl:"
  Random thoughts and musings.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rmulhol.github.io" # the base hostname & protocol for your site
twitter_username: robmulholand
github_username:  rmulhol

# Build settings
markdown: kramdown

theme: jekyll-theme-cayman