# Site settings
title: Rob Learns Ruby
email: robmulholand@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm learning Ruby and sharing insights along the way.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: robmulholand
github_username:  rmulhol

# Build settings
markdown: kramdown
