# Site settings
title: Rob Learns Programming
email: robmulholand@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Notes from a journey on the path toward becoming proficient in computer programming.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rmulhol.github.io/" # the base hostname & protocol for your site
twitter_username: robmulholand
github_username:  rmulhol

# Build settings
markdown: kramdown
